### ISSUE TITLE
Git merge driver

### ISSUE THREAD

**Issue by brook-seaton** [geut/chan#12]
If this had a merge driver for git to automatically resolve merge conflicts, that would be great.

**Comment by dpaez** [comment]
Hi, @brook-seaton 👋 Thanks for using chan!

Regarding the issue, do you have any example use case for a merge driver in chan? or in changelog resolution, I think? The merge driver concept is new, at least to me, and sounds interesting for chan but need more info. Maybe you have something in mind.

Thanks in advance!
