### ISSUE TITLE
Add option to define the branch/tag to compare to

### ISSUE THREAD

**Issue by JacobDB** [geut/chan#32]
We use a self hosted instance of GitLab at my office, and as such, the URLs that get generated by chan don't adhere to the URL structure required by GitLab.

For example, chan might output a URL like:

```
https://git.example.com/:weblinx/my-repository/compare/v1.0.0...HEAD
```

But my server actually requires:

```
https://git.example.com/weblinx/my-repository/compare/v1.0.0...master
```

Being able to pass in something like `--compare master` (preferably also via config file) would solve this.

**Comment by JacobDB** [comment]
Honestly not sure if this is the best solution for this, I'm open to suggestions.

**Comment by JacobDB** [comment]
Found this related issue on GitLab's tracker, will try to get some attention to it &ndash; https://github.com/JacobDB/pwa-install-prompt/compare/v1.0.0...HEAD

**Comment by tinchoz49** [comment]
Hi @JacobDB, on the next version we are going to have support for `--git-template` and `--git-branch`, so you will can to use something like: 
```
chan release <version> --git-template 'https://git.example.com/weblinx/my-repository/compare/[prev]...[next] --git-branch master
```

**Comment by JacobDB** [comment]
Awesome; will there be a way to do this automatically via some kind of config? Maybe something like a `.chanrc`?

**Comment by JacobDB** [comment]
Oh I see, will likely be configurable via the package.json

**Comment by tinchoz49** [comment]
If you want, you can try the next version: `npm install -g @geut/chan@beta` feedback is welcome :smiley:

The next doc is here: https://github.com/geut/chan/tree/v2.0.0-beta/packages/chan

**Comment by JacobDB** [comment]
Looks like this works in the beta channel, closing 🙂
