### ISSUE TITLE
[beta] Parameters don't seem to be read from `.chanrc`

### ISSUE THREAD

**Issue by JacobDB** [geut/chan#34]
I was testing out the latest beta release, and found that I can set the configuration option `get-template` in `package.json`, but not in `.chanrc`. Documentation seems to indicate either should work. https://github.com/geut/chan/issues/new

**Comment by tinchoz49** [comment]
Hi @JacobDB ! can you check the new release?

**Comment by JacobDB** [comment]
Values do seem to be reading from `.chanrc` now, closing.
