### ISSUE TITLE
Error occurs when attempting to create a release when not using GitHub

### ISSUE THREAD

**Issue by JacobDB** [geut/chan#36]
My company uses a self-hosted GitLab server to store our code. When I have my `origin` set to a repository on our GitLab server, I get the following error when runing `chan release ${npm_package_version}`:

```
[chan] [release] › ✖  error     TypeError: Cannot destructure property `template` of 'undefined' or 'null'.
```

**Comment by JacobDB** [comment]
I'm thinking this is likely an issue with `packages/git-url-parse/index.js`, as that's where it's trying to convert the URL, and it only has keys defined for `github`, `bitbucket`, and `gitlab`. It seems like even if a template is set in `package.json` it's still running this code, and therefore erroring.

**Comment by JacobDB** [comment]
This also appears to affect repositories with `origin` set to a GitHub URL when my custom GitLab URL is set in either `.chanrc` or `package.json`.

**Comment by dpaez** [comment]
Hey @JacobDB thanks for all the insights and debugging efforts! They are super helpful.

We will give it a look.

**Comment by tinchoz49** [comment]
Hi @JacobDB we fixed in the release v2.1.0

**Comment by JacobDB** [comment]
Beautiful, seems to be working for me.

**Comment by tinchoz49** [comment]
As always, thank you so much for your feedback.
