### ISSUE TITLE
`--merge-prerelease` doesn't combine lists from unreleased changes

### ISSUE THREAD

**Issue by JacobDB** [geut/chan#42]
For example, if I have this in my CHANGELOG.md:

```markdown
## [Unreleased]
### Added
- One last item for demo

## [0.5.0-a2] - 2019-07-22
### Added
- Hello world

## [0.5.0-a1] - 2019-07-21
### Added
- Testing something
```

The output when running `chan release 0.5.0 --merge-prelease` is:

```markdown
## [0.5.0] - 2019-07-22
### Added
- One last item for demo

### Added
- Hello world
- Testing something
```

As you can see, the unreleased items under "Added" aren't being merged with the two prerelease "Added" headers. This could be worked around by first create a prerelease `0.5.0-a3` or something, but that seems unnecessary to me.

**Comment by tinchoz49** [comment]
Fixed v2.1.1

Side note: I have to start creating functional tests for this edge cases.
