### ISSUE TITLE
Use prettier to format changelog

### ISSUE THREAD

**Issue by shiftgeist** [geut/chan#53]

**Comment by shiftgeist** [comment]
May I ask why the issue has been closed? @elmasse

**Comment by elmasse** [comment]
Sorry, my bad. I removed prettier completely from the repository in favor of using just standardjs and moved all packages into ESM.

Please feel free to re-open it and add more information in case you consider this as something we can do to improve or fix.

Thanks in advance.

**Comment by shiftgeist** [comment]
Thanks for the answer.
