### ISSUE TITLE
Auto detect git repo and create compare url

### ISSUE THREAD

**Issue by elmasse** [geut/chan#6]
We need to detect the git repo for Github, Gitlab and Bitbucket and create the git-compare url automatically.

**Comment by tinchoz49** [comment]
Fixed on the next [v2](https://github.com/geut/chan/tree/v2.0.0-beta) release.

**Comment by tinchoz49** [comment]
closed by: https://github.com/geut/chan/pull/35

**Comment by tinchoz49** [comment]
closed by: https://github.com/geut/chan/pull/35
