### ISSUE TITLE
GitHub Tag URL is just `tag`, not `tags`

### ISSUE THREAD

**Issue by michaeldbianchi** [geut/chan#65]
I think this might only be used for the first release (since other links show the changes between the newly released tag and its previous tag). 

Code: 
https://github.com/geut/chan/blob/4d867eb62d7b4b45e487d2759065e5e4bfbd8d5d/packages/git-url-parse/src/index.js#L10

Reference for GitHub tag url:
https://github.com/geut/chan/releases/tag/v3.2.1

**Comment by tinchoz49** [comment]
Thank you for report this. It was fixed in the latest version.
