### ISSUE TITLE
The `version` prop to do a release is not valid.

### ISSUE THREAD

**Issue by RSickenberg** [geut/chan#69]
Hello, 

When I try to run a `chan xxx` on an legacy changelog, I can't due to an error.
![image](https://user-images.githubusercontent.com/16922548/144075219-7f183e87-d68f-4151-9d1a-cb51e7afe8d3.png)

Here is an example of my `changelog.md`:
![image](https://user-images.githubusercontent.com/16922548/144075311-70672a68-2b9c-40a0-9905-50694bcf9639.png)

**Comment by tinchoz49** [comment]
Hi @RSickenberg is your changelog respecting the keepachangelog standard?

**Comment by RSickenberg** [comment]
Hello @tinchoz49, I manually remade a changelog but, no. It didn't respect the std. 

As a fix, it would be cool to have a more explanatory error :-)

Happy new year!
