### ISSUE TITLE
Improve and Review Error Messages

### ISSUE THREAD

**Issue by elmasse** [geut/chan#8]

**Comment by tinchoz49** [comment]
On the next [v2](https://github.com/geut/chan/tree/v2.0.0-beta) release we improved the messages.

**Comment by dpaez** [comment]
Hello folks, this is maybe related. 
The other day I run `chan updated 'message'` and it didn't throw any error/message. Of course it didn't change the changelog neither. 
It would improve the experience to output a message indicating if a command does not exists. 

Thanks :v:
